# See https://medium.com/google-cloud/migrating-mongodb-to-gke-a-secure-and-scalable-solution-b887a25fce85
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mongodb
data:
  password: cGFzc3dvcmQxMjM= # password123 //<base64-encoded-username>
  username: YWRtaW4= # admin //<base64-encoded-password>
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-storage-class
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: mongodb
spec:
  serviceName: "mongo"
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: mongo-storage-class
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongodb
spec:
  ports:
    - port: 27017
  clusterIP: None
  selector:
    app: mongo
---